"""add language to user settings

Revision ID: d55400ace6d4
Revises: e4807eccbcc6
Create Date: 2026-02-05 15:25:42.951190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55400ace6d4'
down_revision: Union[str, None] = 'e4807eccbcc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('language', sa.String(length=5), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'language')
    # ### end Alembic commands ###
